In [ ]:
import yaml
import pandas as pd
import numpy as np
import gspread
from random import choice
from gspread_dataframe import get_as_dataframe, set_with_dataframe
from sheet import spreadsheet as ss
import xotelo
from datetime import date
pd.set_option('future.no_silent_downcasting', True)
import os
# Get the folder where this script is located
# base_dir = os.path.dirname(os.path.abspath(__file__))
base_dir = os.path.dirname(os.path.abspath("."))

yaml_config_path = os.path.join(base_dir, "HOTELRATES", 'hotels.yml')

with open(yaml_config_path, "r") as f_in:
    HOTELS = yaml.safe_load(f_in)
SHORT_TO_ID = {
    hotel['short']: hotel['id_tripadvisor'] 
    for hotel in HOTELS.values() 
}
SHORT_NAMES = {data['short'] for data in HOTELS.values()}
WORKSHEET = ss.client.open("Prix Aroma").worksheet("config")

def load_config():
    df = get_as_dataframe(WORKSHEET, index_col=0, skip_blank_lines=True, evaluate_formulas=True)
    df['value'] = df['value'].astype('object')
    return df

def reset_update_go(config):
    config.loc["update_go", "value"] = False

def export_config(df):
    set_with_dataframe(
        WORKSHEET,
        df,
        include_index=True
    )

In [3]:
config = load_config()
config.loc["update_go", "value"]

np.float64(0.0)

In [4]:
config.loc["update_go", "value"] = 0

In [20]:
config

                                             Nom  value
config
update_go               Exécuter la mise à jour:    1.0
time_last_update  Dernière mise à jour manuelle:    NaN

In [21]:
reset_update_go(config)

C:\Users\Xuan\AppData\Local\Temp\ipykernel_62932\643281916.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'False' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  config.loc["update_go", "value"] = False

In [22]:
config

                                             Nom  value
config
update_go               Exécuter la mise à jour:  False
time_last_update  Dernière mise à jour manuelle:    NaN

In [5]:
export_config(config)